databases:
  - name: bookstore-db
    databaseName: bookstore
    user: admin
    plan: free

services:
  - type: web
    name: bookstore-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn bookstore.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
